# deliberate error handling 

print ('hello')



# print ('hello)
